require:
  - rubocop-minitest
  - rubocop-rake

inherit_gem:
  rubocop-minitest:
    - config/default.yml
  rubocop-rake:
    - config/default.yml

# Rake:
#   Enabled: true

AllCops:
  DisabledByDefault: true
  NewCops: enable
